"""
NB10 v2 builder: string-concat cells (no nested triple-quotes).
"""
import json, uuid, pathlib

ROOT    = pathlib.Path(".").resolve()
NB_PATH = ROOT / "notebooks" / "10_nrt_lake_monitoring.ipynb"

def cid():
    return str(uuid.uuid4())[:8]

def md(text):
    return {"cell_type": "markdown", "metadata": {}, "source": text.splitlines(keepends=True), "id": cid()}

def code(text):
    return {"cell_type": "code", "execution_count": None, "metadata": {}, "outputs": [], "source": text.splitlines(keepends=True), "id": cid()}

cells = []

# ── Title ─────────────────────────────────────────────────────────────────────
cells.append(md(
    "# GlacierGuard-AI -- Notebook 10\n"
    "## Near-Real-Time Sentinel-1 / Sentinel-2 Lake Monitoring\n\n"
    "**Credential resolution (2-tier, never printed):**\n"
    "1. Environment variables `CDSE_CLIENT_ID` / `CDSE_CLIENT_SECRET`\n"
    "2. `~/.glacierguard/cdse_credentials.json` (outside Git repo)\n\n"
    "To populate the credential file once, run from PowerShell with credentials set:\n"
    "```\n"
    ".venv\\Scripts\\python.exe scratch\\setup_cdse_credentials.py\n"
    "```\n"
))

# ── Imports ────────────────────────────────────────────────────────────────────
cells.append(md("## S2 - Imports\n"))
cells.append(code(
    "import os, sys, json, time, math, struct, pathlib, datetime, warnings\n"
    "import urllib.request, urllib.parse, urllib.error\n"
    "from typing import Optional, Dict, List, Tuple\n"
    "import numpy as np\n"
    "import pandas as pd\n"
    "import matplotlib\n"
    "import matplotlib.pyplot as plt\n"
    "import matplotlib.patches as mpatches\n"
    "from matplotlib.gridspec import GridSpec\n"
    "warnings.filterwarnings('ignore')\n"
    "matplotlib.rcParams.update({\n"
    "    'figure.facecolor':'#0d1117','axes.facecolor':'#161b22',\n"
    "    'axes.edgecolor':'#30363d','text.color':'#e6edf3',\n"
    "    'axes.labelcolor':'#e6edf3','xtick.color':'#8b949e',\n"
    "    'ytick.color':'#8b949e','grid.color':'#21262d',\n"
    "    'grid.alpha':0.6,'font.family':'DejaVu Sans',\n"
    "})\n"
    "ROOT    = pathlib.Path('.').resolve()\n"
    "REPORTS = ROOT / 'reports'\n"
    "REPORTS.mkdir(exist_ok=True)\n"
    "print('Python:', sys.version.split()[0])\n"
    "print('NumPy:', np.__version__, '  Pandas:', pd.__version__)\n"
    "print('Working dir:', ROOT)\n"
))

# ── Credential layer ──────────────────────────────────────────────────────────
cells.append(md(
    "## S3 - Secure Credential Layer\n\n"
    "2-tier lookup: env vars -> `~/.glacierguard/cdse_credentials.json`.\n"
    "Credentials never stored as attributes or printed.\n"
))
cells.append(code(
    "_CRED_FILE = pathlib.Path.home() / '.glacierguard' / 'cdse_credentials.json'\n\n"
    "CDSE_TOKEN_URL = ('https://identity.dataspace.copernicus.eu'\n"
    "                  '/auth/realms/CDSE/protocol/openid-connect/token')\n"
    "SH_TOKEN_URL   = 'https://services.sentinel-hub.com/oauth/token'\n"
    "CDSE_STAC_URL  = 'https://catalogue.dataspace.copernicus.eu/stac/search'\n"
    "SH_PROCESS_URL = 'https://sh.dataspace.copernicus.eu/api/v1/process'\n\n"
    "def _resolve_credentials():\n"
    "    # Returns (client_id, client_secret, source) -- values NEVER printed\n"
    "    cid  = os.environ.get('CDSE_CLIENT_ID',  '')\n"
    "    csec = os.environ.get('CDSE_CLIENT_SECRET', '')\n"
    "    if cid and csec:\n"
    "        return cid, csec, 'environment variable'\n"
    "    if _CRED_FILE.exists():\n"
    "        try:\n"
    "            data = json.loads(_CRED_FILE.read_text(encoding='utf-8'))\n"
    "            cid  = data.get('client_id',     '')\n"
    "            csec = data.get('client_secret', '')\n"
    "            if cid and csec:\n"
    "                return cid, csec, f'credential file ({_CRED_FILE})'\n"
    "        except Exception as exc:\n"
    "            return '', '', f'credential file error: {exc}'\n"
    "    return '', '', 'not found'\n\n"
    "class CDSESession:\n"
    "    # Short-lived bearer token manager. Credentials never stored as plain text.\n"
    "    def __init__(self):\n"
    "        self._token: Optional[str] = None\n"
    "        self._expires_at: float    = 0.0\n"
    "        self._endpoint_name: str   = ''\n\n"
    "    def _acquire_token(self):\n"
    "        cid, csec, source = _resolve_credentials()\n"
    "        if not cid or not csec:\n"
    "            return False, f'Credentials not available (source: {source})'\n"
    "        last_err = 'No endpoints tried'\n"
    "        for name, url in [('CDSE Keycloak', CDSE_TOKEN_URL),\n"
    "                          ('Sentinel Hub',  SH_TOKEN_URL)]:\n"
    "            payload = urllib.parse.urlencode({\n"
    "                'grant_type': 'client_credentials',\n"
    "                'client_id': cid, 'client_secret': csec,\n"
    "            }).encode('utf-8')\n"
    "            req = urllib.request.Request(\n"
    "                url, data=payload,\n"
    "                headers={'Content-Type': 'application/x-www-form-urlencoded',\n"
    "                         'User-Agent': 'GlacierGuard-AI/1.0'})\n"
    "            try:\n"
    "                with urllib.request.urlopen(req, timeout=30) as resp:\n"
    "                    data = json.loads(resp.read().decode('utf-8'))\n"
    "                    if 'access_token' in data:\n"
    "                        self._token         = data['access_token']\n"
    "                        self._expires_at    = time.time() + data.get('expires_in', 300) - 30\n"
    "                        self._endpoint_name = name\n"
    "                        return True, name\n"
    "            except urllib.error.HTTPError as e:\n"
    "                last_err = f'{name} HTTP {e.code}'\n"
    "            except Exception as exc:\n"
    "                last_err = f'{name}: {exc}'\n"
    "        return False, last_err\n\n"
    "    def get_token(self) -> str:\n"
    "        if not self._token or time.time() >= self._expires_at:\n"
    "            ok, msg = self._acquire_token()\n"
    "            if not ok:\n"
    "                raise RuntimeError(f'OAuth failed: {msg}')\n"
    "        return self._token\n\n"
    "    def auth_header(self) -> Dict[str, str]:\n"
    "        return {'Authorization': f'Bearer {self.get_token()}',\n"
    "                'Content-Type': 'application/json',\n"
    "                'User-Agent': 'GlacierGuard-AI/1.0'}\n\n"
    "    @property\n"
    "    def endpoint(self) -> str:\n"
    "        return self._endpoint_name\n\n"
    "print('CDSESession ready.')\n"
))

# ── Credential check + OAuth ──────────────────────────────────────────────────
cells.append(md("## S4 - Credential Check & OAuth\n"))
cells.append(code(
    "cid_env  = os.environ.get('CDSE_CLIENT_ID',  '')\n"
    "csec_env = os.environ.get('CDSE_CLIENT_SECRET', '')\n"
    "cred_file_ok = False\n"
    "if _CRED_FILE.exists():\n"
    "    try:\n"
    "        _d = json.loads(_CRED_FILE.read_text(encoding='utf-8'))\n"
    "        cred_file_ok = bool(_d.get('client_id')) and bool(_d.get('client_secret'))\n"
    "        del _d\n"
    "    except Exception: pass\n\n"
    "print('Credential availability:')\n"
    "print(f'  Env vars available    : {\"YES\" if (cid_env and csec_env) else \"NO\"}')\n"
    "print(f'  Credential file valid : {\"YES\" if cred_file_ok else \"NO\"}')\n"
    "print(f'  Credential file path  : {_CRED_FILE}')\n"
    "_, _, _src = _resolve_credentials()\n"
    "_cid_test, _, _ = _resolve_credentials()\n"
    "print(f'  Resolved source       : {_src}')\n"
    "print(f'  Credentials available : {\"YES\" if _cid_test else \"NO\"}')\n"
    "del cid_env, csec_env, _cid_test, _src\n"
    "print()\n\n"
    "SESSION = CDSESession()\n"
    "try:\n"
    "    _ = SESSION.get_token()\n"
    "    print('AUTHENTICATION : SUCCESS')\n"
    "    print(f'ENDPOINT       : {SESSION.endpoint}')\n"
    "    print('ACCESS TOKEN   : OBTAINED (value hidden)')\n"
    "    print(f'EXPIRES IN     : ~{max(0, int(SESSION._expires_at - time.time()))} seconds')\n"
    "except RuntimeError as e:\n"
    "    print('AUTHENTICATION : FAILURE')\n"
    "    print(f'ERROR          : {e}')\n"
    "    print()\n"
    "    print('FIX: Run from PowerShell with credentials set:')\n"
    "    print('  .venv\\\\Scripts\\\\python.exe scratch\\\\setup_cdse_credentials.py')\n"
))

# ── Lake registry ─────────────────────────────────────────────────────────────
cells.append(md("## S5 - Lake Registry\n"))
cells.append(code(
    "LAKES = [\n"
    "    dict(lake_id='imja_tsho',   display_name='Imja Tsho (Imja Lake)',\n"
    "         bbox=[86.900,27.885,86.955,27.930], historical_area_km2=1.32,\n"
    "         basin='Koshi/Dudh Kosi',  elevation_m=5010, hazard_level='HIGH'),\n"
    "    dict(lake_id='thulagi',     display_name='Thulagi Glacier Lake',\n"
    "         bbox=[84.472,28.524,84.530,28.565], historical_area_km2=0.73,\n"
    "         basin='Gandaki/Marsyangdi', elevation_m=4150, hazard_level='HIGH'),\n"
    "    dict(lake_id='tsho_rolpa',  display_name='Tsho Rolpa Glacier Lake',\n"
    "         bbox=[86.467,27.850,86.520,27.900], historical_area_km2=1.65,\n"
    "         basin='Koshi/Rolwaling', elevation_m=4580, hazard_level='HIGH'),\n"
    "    dict(lake_id='lower_barun', display_name='Lower Barun Glacial Lake',\n"
    "         bbox=[87.077,27.818,87.125,27.858], historical_area_km2=0.48,\n"
    "         basin='Koshi/Arun', elevation_m=4450, hazard_level='MEDIUM'),\n"
    "    dict(lake_id='sabai_tsho',  display_name='Sabai Tsho',\n"
    "         bbox=[86.571,27.794,86.620,27.830], historical_area_km2=0.22,\n"
    "         basin='Koshi/Likhu', elevation_m=4730, hazard_level='LOW'),\n"
    "]\n"
    "print(f'Registered {len(LAKES)} lakes:')\n"
    "for lk in LAKES:\n"
    "    print(f'  {lk[\"lake_id\"]:<20} {lk[\"display_name\"]:<35} '\n"
    "          f'{lk[\"historical_area_km2\"]:.2f} km2  {lk[\"hazard_level\"]}')\n"
))

# ── Catalog helpers ────────────────────────────────────────────────────────────
cells.append(md("## S6 - Catalog Helpers\n"))
cells.append(code(
    "def build_datetime_window(days_back=365):\n"
    "    end   = datetime.datetime.utcnow()\n"
    "    start = end - datetime.timedelta(days=days_back)\n"
    "    return f'{start.strftime(\"%Y-%m-%dT00:00:00Z\")}/{end.strftime(\"%Y-%m-%dT23:59:59Z\")}'\n\n"
    "def stac_search(session, bbox, datetime_range, collection, limit=100):\n"
    "    payload = json.dumps({'collections':[collection],'bbox':bbox,\n"
    "                          'datetime':datetime_range,'limit':limit}).encode()\n"
    "    req = urllib.request.Request(CDSE_STAC_URL, data=payload, headers=session.auth_header())\n"
    "    try:\n"
    "        with urllib.request.urlopen(req, timeout=30) as resp:\n"
    "            return json.loads(resp.read().decode('utf-8'))\n"
    "    except urllib.error.HTTPError as e:\n"
    "        raise RuntimeError(f'STAC HTTP {e.code}: {e.read().decode(\"utf-8\",\"replace\")[:200]}')\n\n"
    "def count_scenes(r):\n"
    "    if 'numberMatched' in r: return int(r['numberMatched'])\n"
    "    if 'context' in r and 'matched' in r['context']: return int(r['context']['matched'])\n"
    "    return len(r.get('features',[]))\n\n"
    "def get_scene_dates(r):\n"
    "    dates = []\n"
    "    for feat in r.get('features',[]):\n"
    "        dt = (feat.get('properties',{}).get('datetime') or\n"
    "              feat.get('properties',{}).get('datetime_range_start',''))\n"
    "        if dt: dates.append(dt[:10])\n"
    "    return sorted(set(dates), reverse=True)\n\n"
    "S1_COLLS = ['SENTINEL-1','sentinel-1-grd']\n"
    "S2_COLLS = ['SENTINEL-2','sentinel-2-l2a']\n"
    "print('Catalog helpers ready.')\n"
))

# ── Catalog test: Imja Tsho ────────────────────────────────────────────────────
cells.append(md(
    "## S7 - Catalog API Test: Imja Tsho\n\n"
    "Tests Sentinel-1 and Sentinel-2 catalog for Imja Tsho only.\n"
    "Multi-lake run is guarded until this passes.\n"
))
cells.append(code(
    "IMJA    = next(lk for lk in LAKES if lk['lake_id']=='imja_tsho')\n"
    "IMJA_DT = '2024-01-01T00:00:00Z/2025-09-29T23:59:59Z'\n"
    "print('='*60)\n"
    "print('CATALOG TEST -- Imja Tsho')\n"
    "print('='*60)\n"
    "print(f'  BBox   : {IMJA[\"bbox\"]}')\n"
    "print(f'  Window : {IMJA_DT}')\n"
    "print()\n"
    "imja_catalog = {}\n"
    "for sensor, colls in [('Sentinel-1',S1_COLLS),('Sentinel-2',S2_COLLS)]:\n"
    "    found = False\n"
    "    for coll in colls:\n"
    "        try:\n"
    "            res   = stac_search(SESSION, IMJA['bbox'], IMJA_DT, coll, limit=100)\n"
    "            n     = count_scenes(res)\n"
    "            dates = get_scene_dates(res)\n"
    "            print(f'  {sensor} ({coll})')\n"
    "            print(f'    Catalog API : SUCCESS')\n"
    "            print(f'    Scene count : {n}')\n"
    "            print(f'    Latest 6    : {dates[:6]}')\n"
    "            imja_catalog[sensor] = {'count':n,'dates':dates}\n"
    "            found = True\n"
    "            break\n"
    "        except Exception as e:\n"
    "            print(f'  {sensor} ({coll}): {e}')\n"
    "    if not found:\n"
    "        imja_catalog[sensor] = {'count':0,'dates':[]}\n"
    "    print()\n"
    "print(f'Sentinel-1 scenes : {imja_catalog[\"Sentinel-1\"][\"count\"]}')\n"
    "print(f'Sentinel-2 scenes : {imja_catalog[\"Sentinel-2\"][\"count\"]}')\n"
))

# ── Processing API helpers ─────────────────────────────────────────────────────
cells.append(md("## S8 - Processing API Helpers\n"))
cells.append(code(
    "ES_S2 = (\n"
    "    '//VERSION=3\\nfunction setup(){'\n"
    "    'return{input:[{bands:[\"B03\",\"B08\",\"SCL\"],units:\"REFLECTANCE\"}],'\n"
    "    'output:{bands:1,sampleType:\"UINT8\"}}}\\n'\n"
    "    'function evaluatePixel(s){'\n"
    "    'var v=[4,5,6];if(v.indexOf(s.SCL[0])<0)return[0];'\n"
    "    'var n=(s.B03[0]-s.B08[0])/(s.B03[0]+s.B08[0]+1e-6);'\n"
    "    'return[n>0.15?1:0]}\\n'\n"
    ")\n\n"
    "ES_S1 = (\n"
    "    '//VERSION=3\\nfunction setup(){'\n"
    "    'return{input:[{bands:[\"VV\"],units:\"LINEAR_POWER\"}],'\n"
    "    'output:{bands:1,sampleType:\"UINT8\"}}}\\n'\n"
    "    'function evaluatePixel(s){'\n"
    "    'var d=10*Math.log10(s.VV[0]+1e-10);'\n"
    "    'return[d<-12.0?1:0]}\\n'\n"
    ")\n\n"
    "def bbox_raster_size(bbox):\n"
    "    lat_mid = (bbox[1]+bbox[3])/2.0\n"
    "    W = max(64,min(512,int((bbox[2]-bbox[0])*111320*math.cos(math.radians(lat_mid))/10)))\n"
    "    H = max(64,min(512,int((bbox[3]-bbox[1])*111320/10)))\n"
    "    return W, H\n\n"
    "def proc_request(bbox, es, coll, d_from, d_to):\n"
    "    W,H = bbox_raster_size(bbox)\n"
    "    return {\n"
    "        'input':{'bounds':{'bbox':bbox,'properties':{'crs':'http://www.opengis.net/def/crs/OGC/1.3/CRS84'}},\n"
    "                 'data':[{'type':coll,'dataFilter':{\n"
    "                     'timeRange':{'from':f'{d_from}T00:00:00Z','to':f'{d_to}T23:59:59Z'},\n"
    "                     'mosaickingOrder':'mostRecent'},\n"
    "                     'processing':{'upsampling':'BILINEAR','downsampling':'BILINEAR'}}]},\n"
    "        'output':{'width':W,'height':H,\n"
    "                  'responses':[{'identifier':'default','format':{'type':'image/tiff'}}]},\n"
    "        'evalscript':es,\n"
    "    }\n\n"
    "def parse_tiff(raw):\n"
    "    try:\n"
    "        e = '<' if raw[:2]==b'II' else '>' if raw[:2]==b'MM' else None\n"
    "        if e is None: return None\n"
    "        ifo = struct.unpack_from(f'{e}I',raw,4)[0]\n"
    "        nt  = struct.unpack_from(f'{e}H',raw,ifo)[0]\n"
    "        tags={}\n"
    "        for i in range(nt):\n"
    "            o=ifo+2+i*12\n"
    "            tag=struct.unpack_from(f'{e}H',raw,o)[0]\n"
    "            typ=struct.unpack_from(f'{e}H',raw,o+2)[0]\n"
    "            val=struct.unpack_from(f'{e}{\"H\" if typ==3 else \"I\"}',raw,o+8)[0]\n"
    "            tags[tag]=val\n"
    "        W,H,s0=tags.get(256),tags.get(257),tags.get(273)\n"
    "        if None in (W,H,s0): return None\n"
    "        px=raw[s0:s0+W*H]\n"
    "        if len(px)<W*H: return None\n"
    "        return np.frombuffer(px,dtype=np.uint8).reshape(H,W)\n"
    "    except: return None\n\n"
    "def px_area_km2(px_count, bbox, shape):\n"
    "    H,W=shape\n"
    "    lm=(bbox[1]+bbox[3])/2.0\n"
    "    return px_count * (bbox[2]-bbox[0])*111320*math.cos(math.radians(lm))/W \\\n"
    "                    * (bbox[3]-bbox[1])*111320/H / 1e6\n\n"
    "print(f'S2 evalscript: {len(ES_S2)} chars')\n"
    "print(f'S1 evalscript: {len(ES_S1)} chars')\n"
    "print('Processing API helpers ready.')\n"
))

# ── monitor_lake() ─────────────────────────────────────────────────────────────
cells.append(md("## S9 - monitor_lake()\n"))
cells.append(code(
    "SH_S2 = 'sentinel-2-l2a'\n"
    "SH_S1 = 'sentinel-1-grd'\n"
    "THRESHOLDS = {0.05:'NORMAL',0.15:'WATCH',0.30:'WARNING',9999:'CRITICAL'}\n\n"
    "def classify(obs, hist):\n"
    "    if hist<=0: return 'UNKNOWN'\n"
    "    f=abs(obs-hist)/hist\n"
    "    for t,s in sorted(THRESHOLDS.items()):\n"
    "        if f<=t: return s\n"
    "    return 'CRITICAL'\n\n"
    "def monitor_lake(lake, session, sensor='S2', days_back=365, verbose=True):\n"
    "    res = {\n"
    "        'lake_id':lake['lake_id'],'display_name':lake['display_name'],\n"
    "        'sensor':sensor,'status':'ERROR',\n"
    "        'observed_area_km2':None,'historical_area_km2':lake['historical_area_km2'],\n"
    "        'abs_change_km2':None,'rel_change_pct':None,'scene_date':None,\n"
    "        'n_scenes_available':0,'water_pixels':0,'total_valid_pixels':0,\n"
    "        'img_shape':None,'bbox':lake['bbox'],'hazard_level':lake['hazard_level'],'errors':[],\n"
    "    }\n"
    "    bbox=lake['bbox']\n"
    "    dtr=build_datetime_window(days_back)\n"
    "    if verbose: print(f'  [{lake[\"lake_id\"]}] {sensor}  {dtr}')\n"
    "    es,sh_coll,colls = (ES_S2,SH_S2,S2_COLLS) if sensor=='S2' else (ES_S1,SH_S1,S1_COLLS)\n"
    "    scene_dates=[]\n"
    "    for coll in colls:\n"
    "        try:\n"
    "            cat=stac_search(session,bbox,dtr,coll)\n"
    "            res['n_scenes_available']=count_scenes(cat)\n"
    "            scene_dates=get_scene_dates(cat)\n"
    "            break\n"
    "        except Exception as e: res['errors'].append(f'Catalog({coll}):{e}')\n"
    "    if not scene_dates:\n"
    "        res['status']='NO_DATA'\n"
    "        if verbose: print('    No scenes found.')\n"
    "        return res\n"
    "    res['scene_date']=scene_dates[0]\n"
    "    if verbose: print(f'    {res[\"n_scenes_available\"]} scenes  latest={scene_dates[0]}')\n"
    "    d0=(datetime.datetime.utcnow()-datetime.timedelta(days=days_back)).strftime('%Y-%m-%d')\n"
    "    d1=datetime.datetime.utcnow().strftime('%Y-%m-%d')\n"
    "    body=proc_request(bbox,es,sh_coll,d0,d1)\n"
    "    req=urllib.request.Request(SH_PROCESS_URL,data=json.dumps(body).encode(),headers=session.auth_header())\n"
    "    raw_tiff=None\n"
    "    try:\n"
    "        with urllib.request.urlopen(req,timeout=90) as resp:\n"
    "            ct=resp.headers.get('Content-Type','')\n"
    "            rb=resp.read()\n"
    "            if verbose: print(f'    ProcessAPI HTTP 200  {ct[:50]}  {len(rb)} B')\n"
    "            if 'multipart' in ct:\n"
    "                bnd=ct.split('boundary=')[-1].strip()\n"
    "                for part in rb.split(f'--{bnd}'.encode()):\n"
    "                    if b'image/tiff' in part or (b'Content-Type' in part and len(part)>50):\n"
    "                        sep=part.find(b'\\r\\n\\r\\n')\n"
    "                        if sep>=0: raw_tiff=part[sep+4:].rstrip(b'\\r\\n-'); break\n"
    "            elif 'tiff' in ct or 'octet' in ct: raw_tiff=rb\n"
    "    except urllib.error.HTTPError as e:\n"
    "        err=e.read().decode('utf-8','replace')\n"
    "        res['errors'].append(f'ProcessAPI HTTP {e.code}: {err[:300]}')\n"
    "        if verbose: print(f'    ProcessAPI ERROR HTTP {e.code}: {err[:200]}')\n"
    "    except Exception as exc:\n"
    "        res['errors'].append(f'ProcessAPI:{exc}')\n"
    "        if verbose: print(f'    ProcessAPI ERROR:{exc}')\n"
    "    if raw_tiff and len(raw_tiff)>100:\n"
    "        arr=parse_tiff(raw_tiff)\n"
    "        if arr is not None:\n"
    "            res['img_shape']=arr.shape\n"
    "            res['water_pixels']=int(np.sum(arr==1))\n"
    "            res['total_valid_pixels']=int(arr.size)\n"
    "            res['observed_area_km2']=px_area_km2(res['water_pixels'],bbox,arr.shape)\n"
    "            if verbose: print(f'    Raster:{arr.shape}  water_px={res[\"water_pixels\"]}  area={res[\"observed_area_km2\"]:.4f} km2')\n"
    "        else:\n"
    "            res['errors'].append('GeoTIFF parse failed')\n"
    "            if verbose: print('    GeoTIFF parse failed.')\n"
    "    else:\n"
    "        sz=len(raw_tiff) if raw_tiff is not None else 0\n"
    "        if raw_tiff is not None: res['errors'].append(f'Raster too small ({sz} B)')\n"
    "        if verbose: print(f'    Empty raster ({sz} B).')\n"
    "    if res['observed_area_km2'] is not None:\n"
    "        h=res['historical_area_km2']; o=res['observed_area_km2']\n"
    "        res['abs_change_km2']=o-h\n"
    "        res['rel_change_pct']=(o-h)/h*100 if h>0 else None\n"
    "        res['status']=classify(o,h)\n"
    "    elif res['n_scenes_available']>0: res['status']='PROCESSING_ERROR'\n"
    "    else: res['status']='NO_DATA'\n"
    "    return res\n\n"
    "print('monitor_lake() ready.')\n"
))

# ── Imja Tsho live test ────────────────────────────────────────────────────────
cells.append(md("## S10 - Imja Tsho Live Test\n"))
cells.append(code(
    "print('='*65)\n"
    "print('LIVE TEST -- Imja Tsho (Sentinel-2)')\n"
    "print('='*65)\n"
    "imja = next(lk for lk in LAKES if lk['lake_id']=='imja_tsho')\n"
    "imja_s2 = monitor_lake(imja, SESSION, sensor='S2', days_back=365, verbose=True)\n"
    "print()\n"
    "for k,v in imja_s2.items():\n"
    "    if k=='errors':\n"
    "        for err in v: print(f'  ERROR: {err}')\n"
    "    elif k!='bbox': print(f'  {k:<28}: {v}')\n"
))
cells.append(code(
    "print('='*65)\n"
    "print('LIVE TEST -- Imja Tsho (Sentinel-1)')\n"
    "print('='*65)\n"
    "imja_s1 = monitor_lake(imja, SESSION, sensor='S1', days_back=365, verbose=True)\n"
    "print()\n"
    "for k,v in imja_s1.items():\n"
    "    if k=='errors':\n"
    "        for err in v: print(f'  ERROR: {err}')\n"
    "    elif k!='bbox': print(f'  {k:<28}: {v}')\n"
    "print()\n"
    "s2_ok = imja_s2.get('observed_area_km2') is not None\n"
    "s1_ok = imja_s1.get('observed_area_km2') is not None\n"
    "print(f'Imja S2: {\"PASS -- \" + str(round(imja_s2[\"observed_area_km2\"],4)) + \" km2\" if s2_ok else \"FAIL (\" + imja_s2[\"status\"] + \")\"}' )\n"
    "print(f'Imja S1: {\"PASS -- \" + str(round(imja_s1[\"observed_area_km2\"],4)) + \" km2\" if s1_ok else \"FAIL (\" + imja_s1[\"status\"] + \")\"}' )\n"
    "print()\n"
    "if s2_ok or s1_ok:\n"
    "    print('IMJA TEST: PASSED -- proceeding to all-lake run.')\n"
    "else:\n"
    "    print('IMJA TEST: FAILED -- resolve errors before proceeding.')\n"
    "    print('Likely cause: Processing API quota or OAuth scope.')\n"
))

# ── Multi-lake run (guarded) ──────────────────────────────────────────────────
cells.append(md("## S11 - Multi-Lake Run (guarded by Imja Tsho pass)\n"))
cells.append(code(
    "if not (s2_ok or s1_ok):\n"
    "    print('Skipping -- Imja Tsho test did not pass.')\n"
    "    monitoring_results = [imja_s2, imja_s1]\n"
    "else:\n"
    "    monitoring_results = []\n"
    "    for lake in LAKES:\n"
    "        print(f'\\n--- {lake[\"display_name\"]} ({lake[\"hazard_level\"]})')\n"
    "        monitoring_results.append(monitor_lake(lake, SESSION, sensor='S2', days_back=365))\n"
    "        monitoring_results.append(monitor_lake(lake, SESSION, sensor='S1', days_back=365))\n"
    "    print(f'\\nTotal runs: {len(monitoring_results)}')\n\n"
    "mon_df = pd.DataFrame(monitoring_results)\n"
    "dc=['lake_id','sensor','status','observed_area_km2','historical_area_km2',\n"
    "    'abs_change_km2','rel_change_pct','scene_date','n_scenes_available']\n"
    "d=mon_df[dc].copy()\n"
    "d['observed_area_km2']=d['observed_area_km2'].map(lambda x:f'{x:.4f}' if x is not None else 'N/A')\n"
    "d['abs_change_km2']   =d['abs_change_km2'].map(   lambda x:f'{x:+.4f}' if x is not None else 'N/A')\n"
    "d['rel_change_pct']   =d['rel_change_pct'].map(   lambda x:f'{x:+.1f}%' if x is not None else 'N/A')\n"
    "print(d.to_string(index=False))\n"
    "mon_df.to_csv(REPORTS/'nrt_monitoring_results.csv', index=False)\n"
    "print(f'CSV saved: {REPORTS}/nrt_monitoring_results.csv')\n"
))

# ── Dashboard ──────────────────────────────────────────────────────────────────
cells.append(md("## S12 - Monitoring Dashboard\n"))
cells.append(code(
    "SC={'NORMAL':'#2ea043','WATCH':'#d29922','WARNING':'#e36b20',\n"
    "    'CRITICAL':'#f85149','NO_DATA':'#484f58','PROCESSING_ERROR':'#8b949e',\n"
    "    'ERROR':'#f85149','UNKNOWN':'#8b949e'}\n"
    "HC={'HIGH':'#f85149','MEDIUM':'#e36b20','LOW':'#2ea043'}\n"
    "df2=mon_df[mon_df['sensor']=='S2'].set_index('lake_id')\n"
    "df1=mon_df[mon_df['sensor']=='S1'].set_index('lake_id')\n"
    "lids=[lk['lake_id'] for lk in LAKES]\n"
    "lnms={lk['lake_id']:lk['display_name'].split('(')[0].strip() for lk in LAKES}\n"
    "hras={lk['lake_id']:lk['historical_area_km2'] for lk in LAKES}\n\n"
    "fig=plt.figure(figsize=(18,14),facecolor='#0d1117')\n"
    "gs=GridSpec(3,3,figure=fig,hspace=0.52,wspace=0.38,top=0.92,bottom=0.07,left=0.07,right=0.97)\n"
    "TKW=dict(color='#e6edf3',fontsize=11,fontweight='bold',pad=10)\n"
    "LKW=dict(color='#8b949e',fontsize=9)\n\n"
    "ax0=fig.add_subplot(gs[0,:]); ax0.set_facecolor('#161b22')\n"
    "ax0.set_title('NRT Monitoring Status Dashboard',**TKW)\n"
    "ax0.set_xlim(-0.5,len(LAKES)-0.5); ax0.set_ylim(-0.5,1.5)\n"
    "ax0.set_yticks([0,1]); ax0.set_yticklabels(['S1 (SAR)','S2 (Optical)'],**LKW)\n"
    "ax0.set_xticks(range(len(LAKES)))\n"
    "ax0.set_xticklabels([lnms[l] for l in lids],rotation=15,ha='right',fontsize=9,color='#e6edf3')\n"
    "ax0.tick_params(axis='both',length=0); ax0.grid(False)\n"
    "for xi,lid in enumerate(lids):\n"
    "    for yi,dfx in enumerate([df1,df2]):\n"
    "        if lid in dfx.index:\n"
    "            st=dfx.loc[lid,'status']\n"
    "            col=SC.get(str(st),'#8b949e')\n"
    "            ax0.add_patch(mpatches.FancyBboxPatch((xi-0.4,yi-0.35),0.8,0.7,\n"
    "                boxstyle='round,pad=0.05',linewidth=0,facecolor=col,alpha=0.85))\n"
    "            ax0.text(xi,yi,str(st),ha='center',va='center',fontsize=8,fontweight='bold',color='white')\n"
    "lp=[mpatches.Patch(color=c,label=s) for s,c in SC.items() if s in ('NORMAL','WATCH','WARNING','CRITICAL','NO_DATA')]\n"
    "ax0.legend(handles=lp,loc='upper right',fontsize=8,framealpha=0.3,facecolor='#0d1117',edgecolor='#30363d')\n\n"
    "ax1=fig.add_subplot(gs[1,:2]); ax1.set_facecolor('#161b22')\n"
    "ax1.set_title('S2 Observed vs. GLO Historical Area',**TKW)\n"
    "x=np.arange(len(lids)); w=0.35\n"
    "hv=[hras[l] for l in lids]\n"
    "ov=[df2.loc[l,'observed_area_km2'] if l in df2.index else None for l in lids]\n"
    "ax1.bar(x-w/2,hv,w,label='Historical (GLO)',color='#388bfd',alpha=0.75,edgecolor='none')\n"
    "ax1.bar(x+w/2,[v if v is not None else 0 for v in ov],w,label='Observed (NRT S2)',\n"
    "        color=[SC.get(str(df2.loc[l,'status']) if l in df2.index else 'NO_DATA','#8b949e') for l in lids],\n"
    "        alpha=0.85,edgecolor='none')\n"
    "ax1.set_xticks(x); ax1.set_xticklabels([lnms[l] for l in lids],rotation=15,ha='right',fontsize=8,color='#e6edf3')\n"
    "ax1.set_ylabel('Area (km2)',**LKW); ax1.legend(fontsize=8,framealpha=0.3,facecolor='#0d1117',edgecolor='#30363d')\n"
    "ax1.tick_params(axis='y',colors='#8b949e'); ax1.spines[:].set_visible(False)\n\n"
    "ax2=fig.add_subplot(gs[1,2]); ax2.set_facecolor('#161b22')\n"
    "ax2.set_title('Delta Area (km2)',**TKW)\n"
    "ch=[df2.loc[l,'abs_change_km2'] if l in df2.index else None for l in lids]\n"
    "cc=['#f85149' if (c is not None and c>0) else '#2ea043' if c is not None else '#484f58' for c in ch]\n"
    "ax2.barh([lnms[l] for l in lids],[c if c is not None else 0 for c in ch],color=cc,alpha=0.85,edgecolor='none')\n"
    "ax2.axvline(0,color='#e6edf3',linewidth=0.8,alpha=0.5); ax2.set_xlabel('Delta Area (km2)',**LKW)\n"
    "ax2.tick_params(axis='both',colors='#8b949e',labelsize=8); ax2.spines[:].set_visible(False)\n\n"
    "ax3=fig.add_subplot(gs[2,:2]); ax3.set_facecolor('#161b22')\n"
    "ax3.set_title('Scene Availability (365 Days)',**TKW)\n"
    "s1c=[df1.loc[l,'n_scenes_available'] if l in df1.index else 0 for l in lids]\n"
    "s2c=[df2.loc[l,'n_scenes_available'] if l in df2.index else 0 for l in lids]\n"
    "ax3.bar(x-w/2,s1c,w,label='S1',color='#e3b341',alpha=0.8,edgecolor='none')\n"
    "ax3.bar(x+w/2,s2c,w,label='S2',color='#388bfd',alpha=0.8,edgecolor='none')\n"
    "ax3.set_xticks(x); ax3.set_xticklabels([lnms[l] for l in lids],rotation=15,ha='right',fontsize=8,color='#e6edf3')\n"
    "ax3.set_ylabel('# Scenes',**LKW); ax3.legend(fontsize=8,framealpha=0.3,facecolor='#0d1117',edgecolor='#30363d')\n"
    "ax3.tick_params(axis='y',colors='#8b949e'); ax3.spines[:].set_visible(False)\n\n"
    "ax4=fig.add_subplot(gs[2,2]); ax4.set_facecolor('#161b22')\n"
    "ax4.set_title('Hazard Level',**TKW)\n"
    "hv2=[3 if lk['hazard_level']=='HIGH' else 2 if lk['hazard_level']=='MEDIUM' else 1 for lk in LAKES]\n"
    "hc2=[HC.get(lk['hazard_level'],'#8b949e') for lk in LAKES]\n"
    "ax4.barh([lnms[l] for l in lids],hv2,color=hc2,alpha=0.85,edgecolor='none')\n"
    "ax4.set_xticks([1,2,3]); ax4.set_xticklabels(['LOW','MED','HIGH'],fontsize=8,color='#8b949e')\n"
    "ax4.tick_params(axis='y',colors='#e6edf3',labelsize=8); ax4.spines[:].set_visible(False)\n"
    "ax4.set_xlabel('Hazard',**LKW)\n\n"
    "fig.suptitle(\n"
    "    f'GlacierGuard-AI -- NRT Lake Monitoring Dashboard\\n'\n"
    "    f'Generated: {datetime.datetime.utcnow().strftime(\"%Y-%m-%d %H:%M UTC\")}',\n"
    "    color='#e6edf3',fontsize=13,fontweight='bold',y=0.98)\n"
    "dp=REPORTS/'nrt_monitoring_dashboard.png'\n"
    "plt.savefig(dp,dpi=150,bbox_inches='tight',facecolor='#0d1117')\n"
    "plt.show(); print(f'Dashboard: {dp}')\n"
))

# ── Time-series ────────────────────────────────────────────────────────────────
cells.append(md("## S13 - Imja Tsho Historical vs NRT\n"))
cells.append(code(
    "HY=[2017,2018,2019,2020,2021,2022,2023,2024]\n"
    "HA=[1.09,1.14,1.18,1.22,1.26,1.29,1.32,1.35]\n"
    "SIG=0.04\n"
    "na=imja_s2.get('observed_area_km2'); nd=imja_s2.get('scene_date'); ns=imja_s2.get('status','?')\n\n"
    "fig,ax=plt.subplots(figsize=(13,5),facecolor='#0d1117')\n"
    "ax.set_facecolor('#161b22')\n"
    "ax.plot(HY,HA,'o-',color='#388bfd',linewidth=2,markersize=6,label='GLO Historical',zorder=3)\n"
    "ax.fill_between(HY,[a-SIG for a in HA],[a+SIG for a in HA],color='#388bfd',alpha=0.15,label=f'+-{SIG} km2')\n"
    "if na is not None:\n"
    "    try: ny=float(nd[:4])+pd.Timestamp(nd).dayofyear/365.25\n"
    "    except: ny=2025.4\n"
    "    ax.scatter([ny],[na],s=180,zorder=5,color=SC.get(ns,'#8b949e'),\n"
    "               edgecolors='white',linewidths=1.5,label=f'NRT ({nd}) [{ns}]')\n"
    "    ax.annotate(f'{na:.3f} km2\\n[{ns}]',xy=(ny,na),xytext=(ny-1.8,na+0.08),\n"
    "                fontsize=9,color='#e6edf3',arrowprops=dict(arrowstyle='->',color='#8b949e',lw=1.2))\n"
    "else:\n"
    "    ax.axhline(hras['imja_tsho'],color='#e36b20',linewidth=1.5,linestyle='--',\n"
    "               label=f'Mean={hras[\"imja_tsho\"]:.2f} km2',alpha=0.6)\n"
    "    ax.text(2023.5,hras['imja_tsho']+0.03,f'NRT:{ns}',color='#8b949e',fontsize=9)\n"
    "ax.set_xlabel('Year',color='#8b949e',fontsize=10)\n"
    "ax.set_ylabel('Area (km2)',color='#8b949e',fontsize=10)\n"
    "ax.set_title('Imja Tsho -- GLO Baseline vs NRT Sentinel-2',color='#e6edf3',fontsize=12,fontweight='bold')\n"
    "ax.legend(fontsize=9,framealpha=0.3,facecolor='#0d1117',edgecolor='#30363d')\n"
    "ax.tick_params(colors='#8b949e'); ax.spines[:].set_color('#30363d'); ax.grid(alpha=0.3)\n"
    "tp=REPORTS/'imja_tsho_area_timeseries.png'\n"
    "plt.tight_layout(); plt.savefig(tp,dpi=150,bbox_inches='tight',facecolor='#0d1117')\n"
    "plt.show(); print(f'Time-series: {tp}')\n"
))

# ── Status report ──────────────────────────────────────────────────────────────
cells.append(md("## S14 - Status Report\n"))
cells.append(code(
    "lines=['='*70,'GLACIERGUARD-AI -- NRT LAKE MONITORING STATUS REPORT',\n"
    "       f'Generated : {datetime.datetime.utcnow().strftime(\"%Y-%m-%d %H:%M:%S UTC\")}',\n"
    "       f'Auth      : {SESSION.endpoint}','Window    : last 365 days','='*70]\n"
    "for lake in LAKES:\n"
    "    lid=lake['lake_id']\n"
    "    lines+=[f'\\n{chr(45)*70}',f'LAKE:{lake[\"display_name\"]}',\n"
    "            f'HAZARD:{lake[\"hazard_level\"]}  HIST:{lake[\"historical_area_km2\"]:.3f} km2']\n"
    "    for sl in ('S2','S1'):\n"
    "        r=next((r for r in monitoring_results if r['lake_id']==lid and r['sensor']==sl),None)\n"
    "        if r is None: continue\n"
    "        lines.append(f'  {sl} [{r[\"status\"]}]')\n"
    "        if r['observed_area_km2'] is not None:\n"
    "            lines.append(f'     area={r[\"observed_area_km2\"]:.4f}  delta={r[\"abs_change_km2\"]:+.4f} ({r[\"rel_change_pct\"]:+.1f}%)')\n"
    "        lines.append(f'     scenes={r[\"n_scenes_available\"]}  latest={r[\"scene_date\"] or \"?\"}')\n"
    "        for err in r.get('errors',[])[:2]: lines.append(f'     WARN:{err[:80]}')\n"
    "lines+=['\\n'+'='*70,'END','='*70]\n"
    "rt='\\n'.join(lines)\n"
    "print(rt)\n"
    "rp=REPORTS/'nrt_monitoring_status_report.txt'\n"
    "with open(rp,'w',encoding='utf-8') as f: f.write(rt)\n"
    "print(f'\\nReport: {rp}')\n"
    "ae=[(r['lake_id'],r['sensor'],e) for r in monitoring_results for e in r.get('errors',[])]\n"
    "print(f'Diagnostics: {len(ae)} warning(s)')\n"
    "for l,s,e in ae[:8]: print(f'  [{l}][{s}] {e[:80]}')\n"
))

# ── Final ──────────────────────────────────────────────────────────────────────
cells.append(md(
    "## S15 - Complete\n\n"
    "Pipeline: env/file creds -> CDSE STAC -> S2 NDWI + S1 VV -> area estimate -> status\n\n"
    "NB01--NB09 (frozen research) + NB10 (operational monitoring) -- ALL COMPLETE\n"
))
cells.append(code(
    "print('='*70)\n"
    "print('GLACIERGUARD-AI -- NOTEBOOK 10 COMPLETE')\n"
    "print('='*70)\n"
    "print(f'Lakes monitored   : {len(LAKES)}')\n"
    "print(f'Credential source : {_resolve_credentials()[2]}')\n"
    "print(f'Outputs           : {REPORTS}')\n"
    "print('NB01-NB10: ALL COMPLETE')\n"
))

# Write
nb = {
    'nbformat': 4, 'nbformat_minor': 5,
    'metadata': {
        'kernelspec': {'display_name':'Python 3','language':'python','name':'python3'},
        'language_info': {'name':'python','version':'3.10.0'},
    },
    'cells': cells,
}
NB_PATH.parent.mkdir(parents=True, exist_ok=True)
with open(NB_PATH, 'w', encoding='utf-8') as f:
    json.dump(nb, f, indent=1, ensure_ascii=False)
print(f"Notebook: {NB_PATH}")
print(f"Cells   : {len(cells)}")
print(f"Size    : {NB_PATH.stat().st_size/1024:.1f} KB")
